language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  # - "pypy" - won't work as smmap doesn't work (see smmap/.travis.yml for details)

install:
  - git submodule update --init --recursive
  - pip install coveralls
script: 
  - nosetests
after_success:
  - coveralls

